#!/bin/bash

# Cleanup Unused TypeScript/TSX Files
# Generated by analysis on $(date)

echo "🧹 Cleaning up unused TypeScript and TSX files..."

# Remove unused dependencies
echo "📦 Removing unused dependencies..."
npm uninstall clsx

# Remove completely unused files (302 lines of code)
echo "🗑️  Removing completely unused files..."

# Backup first (optional)
read -p "Create backup before deletion? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "📋 Creating backup..."
    mkdir -p .unused-files-backup
    cp src/services/speakerDiarization.ts .unused-files-backup/ 2>/dev/null || echo "File already moved"
    cp src/services/tauriIPC.ts .unused-files-backup/ 2>/dev/null || echo "File already moved" 
    cp src/components/index.ts .unused-files-backup/components-index.ts 2>/dev/null || echo "File already moved"
    cp src/components/recording/index.ts .unused-files-backup/recording-index.ts 2>/dev/null || echo "File already moved"
    cp src/features/admin/components/index.ts .unused-files-backup/admin-components-index.ts 2>/dev/null || echo "File already moved"
    cp src/features/meetings/components/index.ts .unused-files-backup/meetings-components-index.ts 2>/dev/null || echo "File already moved"
    cp src/features/meetings/components/status/index.ts .unused-files-backup/status-index.ts 2>/dev/null || echo "File already moved"
fi

# Delete unused files
echo "❌ Deleting unused files..."
rm -f src/services/speakerDiarization.ts
rm -f src/services/tauriIPC.ts
rm -f src/components/index.ts
rm -f src/components/recording/index.ts  
rm -f src/features/admin/components/index.ts
rm -f src/features/meetings/components/index.ts
rm -f src/features/meetings/components/status/index.ts

echo "✅ Cleanup complete!"
echo ""
echo "📊 Summary:"
echo "  - Removed unused dependency: clsx"
echo "  - Deleted 7 unused files (302+ lines of code)"
echo "  - Freed up disk space and reduced bundle size"
echo ""
echo "🔍 Next steps (optional):"
echo "  1. Run 'npx ts-unused-exports tsconfig.json' to clean unused exports"
echo "  2. Run 'npm run build' to verify everything still works"
echo "  3. Use 'npx unimported -u' to update ignore lists"
echo ""
echo "💡 Pro tip: Run this periodically to keep your codebase clean!"
