# version: "3.8"  # Obsolete in Docker Compose v2
services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      ALLOWED_ORIGINS: "*"
      WHISPER_MODEL: ${WHISPER_MODEL:-base}
      WHISPER_COMPUTE_TYPE: ${WHISPER_COMPUTE_TYPE:-auto}
      WHISPER_DOWNLOAD_ROOT: /models
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: ${OLLAMA_MODEL:-llama3.1:8b}
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME:-}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD:-}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - whisper_models:/models

  # Frontend will run on your local computer, not on VPS
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
  #   ports:
  #     - "8080:80"
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

volumes:
  ollama_models:
  whisper_models:

